// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiskbqbasqnbedztuafn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpc2ticWJhc3FuYmVkenR1YWZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzk1NjIsImV4cCI6MjA2MzY1NTU2Mn0.hd4JMTZzk9CcYz222YoVA3WVCPhlx9ixFHQSM_rC0Gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);